### ISSUE TITLE
Incompatibility of runtime features

### ISSUE THREAD

**Issue by timsueberkrueb** [ebkalderon/tower-lsp#358]
First of all, thanks for this useful crate! I ran into a problem when trying to use both runtime features in a workspace.

Cargo features are additive, i.e. when crates depend on the same crate with different features enabled, Cargo will compile the crate with all these features enabled. However, `runtime-tokio` and `runtime-agnostic` are incompatible.

I have a workspace where a crate `A` requires `runtime-tokio` and a crate `B` requires `runtime-agnostic` and both of these crates depend on a crate `C` which contains my lsp server implementation. Basically, `A` exposes the lsp server from `C`  natively, and `B` on the web.

Is there a way to make this work? I tried working around this by specifying `tower-lsp` twice and exposing it via `C`:

```toml
tower-lsp-agnostic = { package = "tower-lsp", version = "0.17", default-features = false, features = ["runtime-agnostic"], optional = true }
tower-lsp-tokio = { package = "tower-lsp", version = "0.17", default-features = false, features = ["runtime-tokio"], optional = true }
```

However, this is also not supported by Cargo:

```
error: the crate `C` depends on crate `tower-lsp v0.17.0` multiple times with different names
````

Now, I can trick Cargo by specifying it once using the git tag `v0.17.0` and once with the corresponding commit hash. However, this does not solve the problem at all, but rather moves it to the `C` crate. There I have to do something like

```rs
#[cfg(feature = "runtime-tokio")]
pub use tower_lsp_tokio as tower_lsp;
#[cfg(feature = "runtime-agnostic")]
pub use tower_lsp_agnostic as tower_lsp;
```

But now, since `C` is compiled only once, `A` and `B` together enable both of these features, meaning `tower_lsp` would be defined twice. The only solution I can think of is moving `C` out of the workspace and tricking Cargo into instantiating two copies of it.

I really hope there's a better solution! Any help or suggestions are highly appreciated!
